grafeas:
  api:
    # Endpoint address
    address: "0.0.0.0:8080"
    # PKI configuration (optional)
    cafile: 
    keyfile: 
    certfile: 
    # CORS configuration (optional)
    cors_allowed_origins:
      # - "http://example.net"
  storage_type: oracle
  oracle:
    # Database host
    host: "localhost:49161"
    # Database name
    dbname: "xe"
    # Database username
    user: "system"
    # Database password
    password: "oracle"
    # Valid sslmodes disable, allow, prefer, require, verify-ca, verify-full.
    # See https://www.postgresql.org/docs/current/static/libpq-connect.html for details
    paginationkey: